{% set name = "beancount" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/beancount-{{ version }}.tar.gz
  sha256: 9f374bdcbae63328d8a0cf6d539490f81caa647f2d1cc92c9fa6117a9eb092ca

build:
  entry_points:
    - bean-check = beancount.scripts.check:main
    - bean-doctor = beancount.scripts.doctor:main
    - bean-example = beancount.scripts.example:main
    - bean-format = beancount.scripts.format:main
    - treeify = beancount.tools.treeify:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - bison >=3.8     # [not win]
    - flex >=2.6.4    # [not win]
    - winflexbison >=2.5.25   # [win]
  host:
    - python
    - meson-python >=0.14.0
    - meson >=1.2.1
    - pip
  run:
    - python
    - click >=7.0
    - python-dateutil >=2.6.0
    - regex >=2022.9.13

test:
  imports:
    - beancount
  commands:
    - pip check
    - bean-check --help
    - bean-doctor --help
    - bean-example --help
    - bean-format --help
    - treeify --help
  requires:
    - pip

about:
  home: https://beancount.github.io/
  summary: Command-line Double-Entry Accounting
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - kklein
